# fly.toml app configuration file generated for django-restaurant on 2024-05-10T13:44:35-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'django-restaurant'
primary_region = 'iad'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'

[[mounts]]
  source = 'django_restaurant'
  destination = '/mnt/django_restaurant'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
